### PR TITLE
Dev_dc1_merge

### PR DESCRIPTION
**Pull request by rameshkoirala**
This pull request is created to eventually merge the result of data-challenge-1 to the master branch of grandlib.

### CODE REVIEW

**Comment by luckyjim** [comment]
I merge dev in dev_dc1_merge and solve conflict, we will see update of granddb dev later
Now I can use conda environment to run GRANDLIB.

**Comment by rameshkoirala** [comment]
@luckyjim the attribute error is because of using the older version of test_efield.root file. Please use the latest version of test_efield.root.

**Comment by rameshkoirala** [comment]
Screen Shot 2023-05-04 at 6 34 00 PM
Screen Shot 2023-05-04 at 6 34 18 PM

**Comment by luckyjim** [comment]
Hello, 
It's ok with last test_efield.root, thank

**Comment by luckyjim** [comment]
Hello, 
is this the desired behavior when putting two the same voltage file as output ?
```
(grandlib-root) jcolley@lpnlp202113:~/projet/grand_wk/merge/grand$ time grand_simu_du.py --verbose error -o test2.root data/test_efield.root 
Traceback (most recent call last):
  File "/home/jcolley/projet/grand_wk/merge/grand/scripts/grand_simu_du.py", line 99, in <module>
    master.compute_event_all()    # saves automatically
  File "/home/jcolley/projet/grand_wk/merge/grand/grand/simu/efield2voltage.py", line 283, in compute_event_all
    self.save_voltage()
  File "/home/jcolley/projet/grand_wk/merge/grand/grand/simu/efield2voltage.py", line 322, in save_voltage
    self.tt_volt.fill()
  File "/home/jcolley/projet/grand_wk/merge/grand/grand/io/root_trees.py", line 1002, in fill
    raise NotUniqueEvent(
grand.io.root_trees.NotUniqueEvent: An event with (run_number,event_number)=(0,1) already exists in the TTree tvoltage.

```

**Comment by luckyjim** [comment]
I must fix this issue

https://github.com/grand-mother/collaboration-issues/issues/30

**Comment by lwpiotr** [comment]
I am not sure if this is the proper way to submit issues with this pull request, but I've created two issues where I mention this branch and also added them to "Development" for this branch.

**Comment by luckyjim** [comment]
Hello @rameshkoirala , @lwpiotr 

the ADC output functionality is expected by users, by Jelena for example I think, I don't see it in this version of merge.

What do you think oliver @grand-oma ?

Thanks

**Comment by lwpiotr** [comment]
What do you mean by the ADC output functionality? Creating a tadc tree from tvoltage, if requested? If it is missing, then I agree it should be there, but it can be added in the next pull request.

**Comment by luckyjim** [comment]
> What do you mean by the ADC output functionality? Creating a tadc tree from tvoltage, if requested?
yes,  I thought it was a feature of your dc1 version, otherwise yes next release

**Comment by lwpiotr** [comment]
Yes, it was a feature of my DC1, but Ramesh rewrote most of the stuff :) So I think the next release.

**Comment by luckyjim** [comment]
Hello, 
Next tuesday I will check output value and may be add a no regression test on DU response.

**Comment by luckyjim** [comment]
Hello, 
Unless I am mistaken, I note a difference in results with master of around 20%, whereas with the dev_ntg version I only have 2.5%. This for DU 24 from test_efield.root. To confirm from my side...

**Comment by luckyjim** [comment]
> The difference compared to what?

- dev_dc1_merge and master
- dev_ntg (like master but with optimization frequency interpolation) and master

**Comment by lwpiotr** [comment]
The master is the version you've pushed before the Nijmegen meeting? Ramesh later did extensive work comparing and fixing the results, so the question is, where is the mistake. @rameshkoirala is master expected to give a correct result here?

**Comment by luckyjim** [comment]
I find the difference, the result of source direction isn't the same, in fact Zenith_dist

for de/master/dev_ntg

```

INFO [grand.simu.master_simu 343] ==============>  Processing DU with id: 24
INFO [grand.simu.du.process_ant 158] Source direction (degree): North_gap=-70.3,         Zenith_dist=87.9
INFO [grand.simu.du.process_ant 158] Source direction (degree): North_gap=-70.3,         Zenith_dist=87.9
INFO [grand.simu.du.process_ant 158] Source direction (degree): North_gap=-70.3,         Zenith_dist=87.9

```

and for dev_dc1_merge

```
INFO [grand.simu.efield2voltage 192] ==============>  Processing DU with id: 24
INFO [grand.simu.du.process_ant 165] Source direction (degree): North_gap=-70.3,         Zenith_dist=87.5
INFO [grand.simu.du.process_ant 165] Source direction (degree): North_gap=-70.3,         Zenith_dist=87.5
INFO [grand.simu.du.process_ant 165] Source direction (degree): North_gap=-70.3,         Zenith_dist=87.5

```

certainly something with altitude of DU.

You found a bug on this calculation and you fixed it in dev_dc1_merge ? 
Where exactly ?

**Comment by lwpiotr** [comment]
I am not sure if there was a bug here. That's why I am asking @rameshkoirala :)

**Comment by lwpiotr** [comment]
Can we generate test_efield.root with 2 events? I would like to see if it works with multi-events files, as i expect this will be the most common case.

**Comment by lwpiotr** [comment]
Can we generate test_efield.root with 2 events? I would like to see if it works with multi-events files, as i expect this will be the most common case.

**Comment by lwpiotr** [comment]
Another thing: I look at the Efield (not the voltage) of the DU 0 and in X and Y it looks identical apart from rescaling. Is it how it came from Matias?

image

**Comment by luckyjim** [comment]
> Another thing: I look at the Efield (not the voltage) of the DU 0

I think you show DU 24 at index 0 of trace array ?

> and in X and Y it looks identical apart from rescaling. Is it how it came from Matias?

Yes unless I'm mistaken, it's because of the linear polarization of the signal:

 $\vec E(t)=E(t) \vec p$

So
 $E_x(t)=E_y(t) \frac{p_x}{p_y}$

**Comment by luckyjim** [comment]
> @luckyjim Looks like a different origin (location) is used to define the LTP frame. What is the lat, lon, and height of the detector layout in dev_ntg calculation?

In principle same code as master/release 22.11
I will check tomorow master and dev_dc1_merge on this definition in code

**Comment by rameshkoirala** [comment]
@luckyjim The major difference in the computation between the dev_ntg branch and the dev_dc1_merge branch is the location of the site (given in Geodetic) and the location of the shower core (given in GRANDCS). dev_ntg computation assumes that the site location and the shower core location are the same, which is not always true and is wrong based on the new root_trees.py. In the example file, the site location is [41.27, 96.53,  0.] in geodetic and the shower core location is [0, 0, 2025] in cartesian wrt to the site location. If you change the core position to [0,0,0] while running the dev_dc1_merge branch, both branches should result in the same result.

**Comment by rameshkoirala** [comment]
This is the result I get if I force the shower core to [0,0,0] in the dev_dc1_merge branch to compare it with the dev_ntg branch. As you can see the results are the same.
Screen Shot 2023-05-26 at 2 50 17 PM

**Comment by luckyjim** [comment]
So, GRAND ROOT stores the antenna position and the xmax position **in a different frame**, the consistency test implemented above by setting z xmax  read from the ROOT file to the same z as the antenna is not correct.

**Comment by luckyjim** [comment]
For my part before doing the merge,

-  I will make a correction to this  

  https://github.com/grand-mother/grand/pull/59#issuecomment-1536008946

-   I will remove this useless debug code in production, calculating the self.voc with inverse FFT

https://github.com/grand-mother/grand/blob/e84c92cedd3bd6ca070ca0f3a1f230ad77d8ae4d/grand/simu/efield2voltage.py#L226

- I will check that the script options/comments of grand_simu_du. py are correct with of this merge/refactoring branch

https://github.com/grand-mother/grand/blob/dev_dc1_merge/scripts/grand_simu_du.py
  
  After the merge to do a release , grandlib should integrate as quickly as possible

-    the 2 ns resampling functionality and the 14-bit signal digitization to have data analogous to the detectors

- update of grand_ioroot.py for ROOT file multi-events

**Pull request merged**
